"""create initial tables

Revision ID: 5161f0c8cf13
Revises: 
Create Date: 2026-05-19 20:50:11.080803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5161f0c8cf13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('initial_lives', sa.Integer(), nullable=False),
    sa.Column('paddle_width', sa.Integer(), nullable=False),
    sa.Column('ball_speed', sa.Float(), nullable=False),
    sa.Column('max_ball_speed', sa.Float(), nullable=False),
    sa.Column('speedup_every', sa.Integer(), nullable=False),
    sa.Column('speedup_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('difficulty_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_difficulty_presets_slug'), ['slug'], unique=True)

    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_number'), ['number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('level_reached', sa.Integer(), nullable=False),
    sa.Column('max_balls', sa.Integer(), nullable=False),
    sa.Column('lives_left', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_results_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_results_difficulty'))

    op.drop_table('game_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_number'))

    op.drop_table('levels')
    with op.batch_alter_table('difficulty_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_difficulty_presets_slug'))

    op.drop_table('difficulty_presets')
    # ### end Alembic commands ###
