"""add balls count to levels

Revision ID: 7a3d42c56e53
Revises: 5161f0c8cf13
Create Date: 2026-05-23 20:40:38.010067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3d42c56e53'
down_revision = '5161f0c8cf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balls_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('balls_count')

    # ### end Alembic commands ###
